- name: start jenkins
  shell: service jenkins stop

- copy: src=jenkins.tar.gz dest=/tmp/jenkins.tar.gz

- name: Descomprimir jenkins
  shell: tar -xvzf /tmp/jenkins.tar.gz 
         chdir=/var/lib/jenkins

- user: name=jenkins generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

#add de revers proxi on nginx

# - name: add super powers to jenkins
# - lineinfile: dest=/etc/sudoers  insertafter="includedir /etc/sudoers.d" line='jenkins ALL=(ALL) NOPASSWD: ALL'

- name: start jenkins
  shell: service jenkins start