# - name: Clone repositorio
#   #git: repo=git@github.com:mullerivan/mullerivan.git dest=/home/ivan/mullerivan accept_hostkey=yes
#   git: repo=https://github.com/mullerivan/mullerivan.git dest=/home/vagrant/mullerivan accept_hostkey=yes
#   sudo: false
  
# - name: bundle install (install the rest of the gems)
#   shell: bundle
#          chdir=/home/vagrant/mullerivan
#   sudo: false

 - copy: src=mullerivan.com dest=/etc/nginx/sites-available/mullerivan.com 