- name: Clone repositorio
  git: repo=https://github.com/mullerivan/mullerivan.git dest={{app_path}} accept_hostkey=yes
  sudo: false
  # sudo_user
- name: bundle install (install the rest of the gems)
  shell: /usr/local/rvm/wrappers/default/bundle
         chdir={{app_path}}
  sudo: false
# sudo_user

- copy: src=mullerivan.com dest=/etc/nginx/sites-available/mullerivan.com 

- file: src=/etc/nginx/sites-available/mullerivan.com  dest=/etc/nginx/sites-enabled/mullerivan.com  state=link

- lineinfile: dest=/etc/nginx/sites-available/mullerivan.com  regexp="root my_app/public;" line="root {{app_path}}/public;"

- name: rake db:migrate
  shell: /usr/local/rvm/wrappers/default/rake db:migrate RAILS_ENV=production
         chdir={{app_path}}
  sudo: false

- name: assets:precompile
  shell: /usr/local/rvm/wrappers/default/rake assets:precompile
         chdir={{app_path}}
  sudo: false

- name: change owner
  command: chown "{{user_deploy}}":"{{user_deploy}}" -R  {{app_path}}

- name: Reload nginx
  shell: sudo service nginx reload
  sudo: true

#restar server
