- name: Create  user {{mullerivan_user_deploy}}
  user: name={{mullerivan_user_deploy}}  comment="create user {{mullerivan_user_deploy}}" state=present system=yes createhome=yes shell=/bin/mullerivan_user_deployh

- name: change owner
  command: chown {{mullerivan_user_deploy}}:{{mullerivan_user_deploy}} -R   /home/{{mullerivan_user_deploy}}/

- name: Clone {{mullerivan_user_deploy}}
  git: repo=https://github.com/mullerivan/mullerivan.git dest={{mullerivan_app_path}} accept_hostkey=yes
  sudo: false

- name: bundle install (install the rest of the gems)
  shell: /usr/local/rvm/wrappers/default/bundle
         chdir={{mullerivan_app_path}}
  sudo: false

- name: rake db:migrate
  shell: /usr/local/rvm/wrappers/default/rake db:migrate RAILS_ENV=production
         chdir={{app_path}}
  sudo: false

- name: assets:precompile
  shell: /usr/local/rvm/wrappers/default/rake assets:precompile
         chdir={{app_path}}
  sudo: false

- name: Copy config file nginx => /etc/nginx/sites-available/mullerivan.com 
  copy: src=mullerivan.com dest=/etc/nginx/sites-available/mullerivan.com 

- name: simbolic link => /etc/nginx/sites-enabled/mullerivan.com
  file: src=/etc/nginx/sites-available/mullerivan.com  dest=/etc/nginx/sites-enabled/mullerivan.com  state=link

- name: edit file nginx with path => {{mullerivan_app_path}}/public
  lineinfile: dest=/etc/nginx/sites-available/mullerivan.com  regexp="root my_app/public;" line="root {{mullerivan_app_path}}/public;"

- name: change owner to {{mullerivan_user_deploy}}
  command: chown "{{mullerivan_user_deploy}}":"{{mullerivan_user_deploy}}" -R  {{mullerivan_app_path}}

- name: Reload nginx
  shell: sudo service nginx reload  
