- name: Clone repositorio
  git: repo={{git_repositorie}} dest={{rails_app_path}} accept_hostkey=yes
  sudo: false
  # sudo_user
- name: bundle install (install the rest of the gems)
  shell: /usr/local/rvm/wrappers/default/bundle
         chdir={{rails_app_path}}
  sudo: false
# sudo_user

- copy: src=rails_nginx_conf dest=/etc/nginx/sites-available/{{app_name}}

- file: src=/etc/nginx/sites-available/{{app_name}}  dest=/etc/nginx/sites-enabled/{{app_name}}  state=link

- lineinfile: dest=/etc/nginx/sites-available/{{app_name}}  regexp="root my_app/public;" line="root {{rails_app_path}}/public;"
- lineinfile: dest=/etc/nginx/sites-available/{{app_name}}  regexp="www.xxx.com" line="server_name {{app_name_url}};"

- name: rake db:migrate
  shell: /usr/local/rvm/wrappers/default/rake db:migrate RAILS_ENV=production
         chdir={{rails_app_path}}
  sudo: false


- name: assets:precompile
  shell: /usr/local/rvm/wrappers/default/rake assets:precompile
         chdir={{rails_app_path}}
  sudo: false
# rake assets:precompile
# 
# restar server
- name: reload nginx
  shell: service nginx reload
  sudo: true
