- name: ingenyo
  hosts: ingenyo
  user: root
  sudo: true
  roles:
   # - system
   # - architecture
   # - firewall
#    - fail2ban
   # - createuser
   # - deploy
  vars_files:
    - vars/default.yml  
#ansible-playbook  ingenyo.yml -i hosts/ingenyo  --ask-sudo-pass -vvvv
