- name: ingenyo
  hosts: ivan
  user: ivan
  sudo: true
  roles:
#    - architecture
    - firewall
#    - fail2ban
#    - createuser
  vars:
    user: seba
    ignoreip: 1.2.3.4
    mail_fail2band: mullerivan@gmail.com




#NO ENTENDES?
#DOCUMENTACION!
#http://docs.ansible.com/
#todos los modulos que hay para usar!
#http://docs.ansible.com/list_of_all_modules.html
