- name: remomve things that i dont use
  action: apt pkg={{item}} state=absent
  with_items:
    - thunderbird  
    - hexchat
    - brasero
    - banshee
    - transmission-common
    - transmission-gtk
    - gthumb
    - gthumb-data

- name: Install local-essential packages just for my PC
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - nfs-kernel-server
  - skype

- name: config mi dotfiles
  shell: sh /home/ivan/projectos/dotfiles/setup.sh
  sudo: true



