---
- name: Install nginx
  apt: pkg=nginx state=latest

- name: Remove the default app
  command: rm -rf /etc/nginx/sites-enabled/default

- name:  downloading the GPG signature
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 561F9B9CAC40B2F7
  sudo: true

- name: Install apt-transport-https  and ca-certificates
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - apt-transport-https 
  - ca-certificates
  sudo: true

- copy: src=passenger.list dest=/etc/apt/sources.list.d/passenger.list owner=root group=root mode=600

- name: Install passenger and nginx-extras
  apt: pkg={{ item }} state=latest update_cache=yes install_recommends=yes
  with_items:
  - nginx-extras 
  - passenger
  sudo: true

- name: Restart nginx
  action: service name=nginx state=restarted

- name: config environment rails gem version
  lineinfile: dest=/etc/nginx/nginx.conf  regexp="passenger_root" line="passenger_root /usr/lib/ruby/vendor_ruby/phusion_passenger/locations.ini;"

