# ---
- name:  downloading the GPG signature
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

- name: Installing rvm ruby and rails take 16m5.124s up to your  internet conection
  shell: \curl -sSL https://get.rvm.io | bash -s stable --rails

# - name: do rvm working
#   shell: `source /home/vagrant/.rvm/scripts/rvm`
  

# Ruby from source playbook (https://github.com/jgrowl/ansible-playbook-ruby-from-src)
- name: upgrade
  action: apt update_cache=yes upgrade=yes

- name: install ruby dependencies 
  action: apt pkg={{item}} state=installed
  with_items:
    - build-essential
    - automake
    - bison
    - autoconf
    - pkg-config
    - libreadline6
    - libreadline6-dev
    - openssl
    - libssl-dev
    - curl
    - git-core
    - zlib1g
    - zlib1g-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt1-dev
    - curl

- name: Install app dependencies 
  action: apt pkg={{item}} state=installed
  with_items:
    - libpq-dev
    - nodejs
    - imagemagick
  tags: package

#   # Install correct version of ruby from source
# - name: ruby-from-src | ensure directory temporary ruby download directory is present
#   file: state=directory path={{rubyTmpDir}}

# - name: ruby-from-src | Download ruby source 
#   get_url: url={{rubyUrl}} dest={{rubyTmpDir}}

# - name: ruby-from-src | ensure ruby is extracted
#   command: tar -xf {{rubyCompressedFile}} chdir={{rubyTmpDir}} creates={{tmpRubyPath}}

# - name: ruby-from-src | ensure ruby is configured
#   command: ./configure chdir={{tmpRubyPath}} creates={{tmpRubyPath}}/Makefile

# - name: ruby-from-src | ensure ruby is compiled
#   command: make chdir={{tmpRubyPath}} creates={{tmpRubyPath}}/ruby

# - name: ruby-from-src | ensure ruby is installed
#   command: make install chdir={{tmpRubyPath}} creates=/usr/local/bin/ruby

# - name: Install Bundler
#   command: gem install bundler