---
# tasks file for timezone
- name: set /etc/localtime
  copy: src=/usr/share/zoneinfo/{{ timezone }}
        dest=/etc/localtime
        owner=root
        group=root
        mode=0644
  sudo: true

- name: set /etc/timezone
  copy: dest=/etc/timezone content="{{ timezone }}"
  sudo: true
  notify: update tzdata
