# Local-just-for-my-pc
local-essential: false
# System
system: false
#Arquitecture
essential: false
python: false
rvm: false
nginx_and_passenger: false
jenkins: false
#database
postgresql: false
#console
ohmyzsh: false
#Jenkins
jenkins_app_deploy: false
#IPTABLES
load_defaul_config: true
persist_iptables_on_reboot: true
#mullerivan.com
mullerivan_app_deploy: false
mullerivan_user_deploy: ivan
mullerivan_app_path: /u/apps/mullerivan
#Generic rails deploy
rails_app_deploy: false
rails_user_deploy: rails
rails_app_path: /u/apps/rails_app
rails_git_repositorie: https://github.com/mullerivan/camara-webRT
rails_app_name: camara-webRT
rails_app_name_url: www.camara.com.dev
# Create user
user: ivan
#Fail2Band
ignoreip: 1.2.3.4
mail_fail2band: mullerivan@gmail.com
