#Arquitecture
essential: true
python: true
rvm: true
nginx_and_passenger: true
jenkins: true

app_path: /home/vagrant/mullerivan
#Generic rails deploy
rails_app_path: /home/vagrant/camara
git_repositorie: https://github.com/mullerivan/camara-webRT
app_name: camara-webRT
app_name_url: www.camara.com.dev
#IPTABLES
load_defaul_config: true
persist_iptables_on_reboot: true