# Local-just-for-my-pc
local-essential: true
# System
system: false
#Arquitecture
essential: false
python: false
rvm: false
nginx_and_passenger: false
jenkins: false
#database
postgresql: false
postgresql_user: vagrant
postgresql_db_name: vagrant
postgresql_pass: vagrant
#console
ohmyzsh: false
user: ivan  ##same user for # Create user
#Jenkins
jenkins_app_deploy: false
#IPTABLES
load_defaul_config: true
persist_iptables_on_reboot: true
#mullerivan.com
mullerivan_app_deploy: false
mullerivan_user_deploy: ivan
mullerivan_app_path: /u/apps/mullerivan
#Generic rails deploy
rails_app_deploy: false
rails_user_deploy: mincam
rails_app_path: /u/apps/mincam
rails_git_repositorie: https://github.com/mullerivan/camara-webRT.git
rails_app_name: mincam
rails_app_name_url: www.mincam.raspberry
#Fail2Band
ignoreip: 1.2.3.4
mail_fail2band: mullerivan@gmail.com

