---
- name: save iptables config
  shell: /sbin/iptables-save > /etc/iptables.rules

- copy: src=iptables dest=/etc/network/if-up.d/iptables

- name: make executable
  shell: chmod +x /etc/network/if-up.d/iptables
  
#- lineinfile: dest=/etc/rc.local  insertbefore="exit 0" line="iptables-restore < /etc/iptables.rules"


# - name: copy loadiptables
#   copy: src=loadiptables dest=/etc/network/if-up.d/loadiptables owner=root group=root mode=751

# - name: copy saveiptables
#   copy: src=saveiptables dest=/etc/network/if-down.d/saveiptables owner=root group=root mode=751


